language: ruby
rvm:
- 2.7.0
install:
    - bundle install
    - nvm install node
    - npm i -g yarn
    - yarn install
before_script:
    — bundle exec rails db:create
    — bundle exec rails db:migrate
script:
    — bundle exec rails test